#!/bin/bash

#Function for the System Admin Menu
sysAdmin(){
	#Makes the gui for the System Admin menu
	yad --form --width=250 --text="System Admin Menu:" \
        --field="List all running processes":fbtn "2" \
        - field="List all running services":fbtn "3" \
        --field="List all installed software":fbtn "4" \
        --field="List all users":fbtn "5" \
        --field="Return to main menu":fbtn "6" \
        --button=gtk-cancel:1
	selection=$?
	
	#Case statement to figure out which option the user picked
	case "$selection" in
		#Lists all running processes
		"1") clear; ps -aux | less;;
		#Lists all running services
		"2") clear; service --status-all | grep + | less;;
		#Lists all installed software
		"3") clear; dpkg -l | less;;
		#Lists all users
		"4") clear; awk -F':' '{print $1",",$3",",$4",",$6",",$7}' /etc/passwd | less;;
		#Returns user to the main menu
		"5") clear; mainMenu;;
		#Exits the program
		"6") exit;;
		*);;
	esac
}
#Function for the Security Admin Menu
secAdmin(){
	#Makes the gui for the Security Admin Menu
        yad --form --width=250 --text="Security Admin Menu" \
        --field="List last 10 logged in users":fbtn "2" \
        - field="Print the last 20 lines of an arbitrary file in the /var/log/ directory":fbtn "3" \
        --field="Run the command: netstat -apn --inet":fbtn "4" \
        --field="Use lsof to print the details of a specific process or process ID provided by the user":fbtn "5" \
        --field="Return to main menu":fbtn "6" \
        --button=gtk-cancel:1
	selection=$?
	#Case statement to figure out which option the user picked
	case "$selection" in
		#Lists last 10 logged in users
		"1") clear; last -n 10 | less;;
		#Prints the last 20 lines of a user difined file
		"2")
			clear
			ls -p /var/log/ | grep -v /
			echo -n "Enter the name of the file: "
			read file
			clear
			head -10 /var/log/$file | less;;
		#Runs the command netstat -apn --inet
		"3") clear; netstat -apn --inet | less;;
		#Uses lsof to print the details of a specific process or process ID provided by the user
		"4")
			clear
			ps -aux
			echo -n "Enter of the PID of the process: "
			read pid
			clear
			lsof -p $pid | less;;
		#Returns user to the main menu
		"5") mainMenu;;
		#exits the program
		"6") exit;;
		*);;
	esac
}
#Function for Main Menu 
mainMenu(){
	#Makes the gui for the Main Menu
        yad --text="Main menu:"\
        --button="System Admin":1\
        --button="Security Admin":2\
        --button="Exit":3

        options=$?
        case "$options" in
		#Sends the user to the System Admin Menu
		"1") sysAdmin;;
		#Sends the user to the Security Admin Menu
		"2") secAdmin;;
		#Exits the program
		"3") exit;;
		*);;
        esac
}
