#!/bin/bash
#Lists all running processes
listProc(){
	yad --title="Running Processes" --text="$(ps all)"
	sysAdmin
}
#Lists all running services
listServ(){
	yad --text="$(service --status-all | grep +)"
	sysAdmin
}
#Lists all installed software
listSoft(){
	yad --text="$(dpkg -l)"
	sysAdmin
}
#Lists all users
listUser(){
	yad --text="$(awk -F':' '{print $1",",$3",",$4",",$6",",$7}' /etc/passwd)"
	sysAdmin
}
#Function for the System Admin Menu
sysAdmin(){
	#Makes the gui for the System Admin menu
	yad --title="System Admin Menu" --text="Pick and option:" \
        --button="List all running processes":1\
        --button="List all running services":2\
        --button="List all installed software":3\
        --button="List all users":4\
        --button="Return to main menu":5\
	--button="Exit":6
	selection=$?
	
	#Case statement to figure out which option the user picked
	case "$selection" in
		#Lists all running processes
		"1") listProc;;
		#Lists all running services
		"2") listServ;;
		#Lists all installed software
		"3") listSoft;;
		#Lists all users
		"4") listUser;;
		#Returns user to the main menu
		"5") mainMenu;;
		#Exits the program
		"6") exit;;
		*);;
	esac
}
#Lists last 10 logged in users
listLogs(){
	yad --text="$(last -n 10)"
	secAdmin
}
#Prints the last 20 lines of a user difined file
print20(){
	file=`yad --text="$(ls -p /var/log/ | grep -v /) \nEnter the name of the file" --entry`
	yad --text="$(head -10 /var/log/$file)"
	secAdmin
}
#Runs the command netstat -apn --inet
runNet(){
	yad --text="$(netstat -apn --inet)"
	secAdmin
}
#Uses lsof to print the details of a specific process or process ID provided by the user
printInfo(){
	pid=`yad --text="$(ps all) \nEnter of the PID of the process" --entry`
	yad --text="$(lsof -p $pid)"
	secAdmin
}
#Function for the Security Admin Menu
secAdmin(){
	#Makes the gui for the Security Admin Menu
        yad --title="Security Admin Menu" --form --width=250 --text="Pick an option" \
        --field="List last 10 logged in users":fbtn "1" \
        - field="Print the last 20 lines of an arbitrary file in the /var/log/ directory":fbtn "2" \
        --field="Run the command: netstat -apn --inet":fbtn "3" \
        --field="Use lsof to print the details of a specific process or process ID provided by the user":fbtn "4" \
        --field="Return to main menu":fbtn "5" \
	--field="Exit":fbtn "6"
	selection=$?
	#Case statement to figure out which option the user picked
	case "$selection" in
		#Lists last 10 logged in users
		"1") listLogs;;
		#Prints the last 20 lines of a user difined file
		"2")print20;;
		#Runs the command netstat -apn --inet
		"3") runNet;;
		#Uses lsof to print the details of a specific process or process ID provided by the user
		"4") printInfo;;
		#Returns user to the main menu
		"5") mainMenu;;
		#exits the program
		"6") exit;;
		*);;
	esac
}
#Function for Main Menu 
mainMenu(){
	#Makes the gui for the Main Menu
        yad --Title="Main Menu" --text="Select an option:"\
        --button="System Admin":1\
        --button="Security Admin":2\
        --button="Exit":3
	#this variable captures what button the user clicks
	options=$?
	#A case statement to send the user to where they selected
        case "$options" in
		#Sends the user to the System Admin Menu
		"1") sysAdmin;;
		#Sends the user to the Security Admin Menu
		"2") secAdmin;;
		#Exits the program
		"3") exit;;
		*);;
        esac
}
mainMenu
